version: '3.6'
services:

  trxusdt:
    restart: always
    image: "digibot:0.0.2"
    volumes:
      - ./config/trxusdt.yml:/home/app/config/strategies.yml
    command: bash -c "bundle exec ./bin/bot start"
    logging:
      driver: "json-file"
      options:
          max-size: "50m"

  jstusdt:
    restart: always
    image: "digibot:0.0.2"
    volumes:
      - ./config/jstusdt.yml:/home/app/config/strategies.yml
    command: bash -c "bundle exec ./bin/bot start"
    logging:
      driver: "json-file"
      options:
          max-size: "50m"

  bakeusdt:
    restart: always
    image: "digibot:0.0.2"
    volumes:
      - ./config/bakeusdt.yml:/home/app/config/strategies.yml
    command: bash -c "bundle exec ./bin/bot start"
    logging:
      driver: "json-file"
      options:
          max-size: "50m"

  btcusdt:
    restart: always
    image: "digibot:0.0.2"
    volumes:
      - ./config/btcusdt.yml:/home/app/config/strategies.yml
    command: bash -c "bundle exec ./bin/bot start"
    logging:
      driver: "json-file"
      options:
          max-size: "50m"

  maticusdt:
    restart: always
    image: "digibot:0.0.2"
    volumes:
      - ./config/maticusdt.yml:/home/app/config/strategies.yml
    command: bash -c "bundle exec ./bin/bot start"
    logging:
      driver: "json-file"
      options:
          max-size: "50m"

  bnbusdt:
    restart: always
    image: "digibot:0.0.2"
    volumes:
      - ./config/bnbusdt.yml:/home/app/config/strategies.yml
    command: bash -c "bundle exec ./bin/bot start"
    logging:
      driver: "json-file"
      options:
          max-size: "50m"

  ethusdt:
    restart: always
    image: "digibot:0.0.2"
    volumes:
      - ./config/ethusdt.yml:/home/app/config/strategies.yml
    command: bash -c "bundle exec ./bin/bot start"
    logging:
      driver: "json-file"
      options:
          max-size: "50m"

  dogeusdt:
    restart: always
    image: "digibot:0.0.2"
    volumes:
      - ./config/dogeusdt.yml:/home/app/config/strategies.yml
    command: bash -c "bundle exec ./bin/bot start"
    logging:
      driver: "json-file"
      options:
          max-size: "50m"

  wavesusdt:
    restart: always
    image: "digibot:0.0.2"
    volumes:
      - ./config/wavesusdt.yml:/home/app/config/strategies.yml
    command: bash -c "bundle exec ./bin/bot start"
    logging:
      driver: "json-file"
      options:
          max-size: "50m"

  cakeusdt:
    restart: always
    image: "digibot:0.0.2"
    volumes:
      - ./config/cakeusdt.yml:/home/app/config/strategies.yml
    command: bash -c "bundle exec ./bin/bot start"
    logging:
      driver: "json-file"
      options:
          max-size: "50m"
