log_level: INFO                                           # Level of Arke log info
accounts:
#---------------------------{source}-----------------------------------
- id: binance_source                                      # Unique account id of the source
  driver: binance                                         # One of supported sources drivers
  delay: 1                                                # Delay of balance information update
  key: ""                                                 # API key from source (not required for copy strategy)
  secret: ""                                              # Secret from API key from source (not required for copy strategy)

#---------------------------{target}-----------------------------------
- id: market_target                                    # Unique account id of the target
  driver: nusabot                                         # Only supported target driver
  key: "key_id"                                 # API key from the target, required
  secret: "secret_id"              # Secret from API key from the target, required
  host: ""                   # Your target URL
  ws: ""                       # Your target WebSocet URL
  delay: [5,4,3,2,1,3]                                  # Delay of balance information update

strategies:
#---------------------------{strategy}-----------------------------------
- id: copy-BAKEIDR                                        # Name of a strategy
  type: simple-copy                                       # Type of the strategy
  debug: false                                            # True to see extra Bot logs
  enabled: true                                           # True to run this strategy after Bot (re)startgit
  period: 5                                               # Period of order book refresh
  params:
    spread_bids: 0.003                                    # Percentage difference from the best price on buy side
    spread_asks: 0.003                                    # Percentage difference from the best price on sell side
    balance_base_perc: 0.3                                # Percentage of the balance to use in Asks side
    balance_quote_perc: 0.3                               # Percentage of the balance to use in Bids side
    levels_price_step: 1                                  # Minimum price difference between levels
    levels_price_func: linear                             # Function to use for levels price step from the level, possibles values are constant, linear, exp
    limit_asks_base: 5000                                 # The amount of base currency that will be placed for sale in the order book, if have enough balance
    limit_bids_base: 5000                                 # The amount of base currency that will be placed for buy in the order book, if have enough balance in quote currency equivalent
    max_amount_per_order: 200                             # Limit amount of base currency per order (the small amount are, the bigger number of orders at the same price will be created)
    levels_size: 1                                        # Minimum price difference between price points
    levels_count: 50                                      # Maximum amount of price points that may be created
    side: both                                            # Side, ask, bid or both to apply the strategy on
    random: 0.3                                           # Random factor to apply to every level, default is 0.3 for 30%
    levels: [0.1, 0.2, 1, 2, 0.1]                         # Levels pattern to use in case of custom shape. (ex: [0.1, 0.2, 1, 2, 0.1])
    shape: V                                              # Pattern to be used to generate the orderbook, possible values are v, w and custom

#---------------------------{fixer-dynamic}-----------------------------------
  fx:
    type: fixer                                           # Set Fixer for dynamic conversion rate take from forex
    api_key: wnENK1RfRUmt3BVyLZYAWiuFyoxb4JuJ             # Your key (without brackets) from https://fixer.io/ to request conversion rate
    currency_from: USD                                    # Source exchange currency you are converting from
    currency_to: IDR                                      # Target exchange currency you are converting to
    period: 3600                                          # Period of converting rate refresh
  target:
    account_id: digiasset_target                          # Unique account id, from the account section, that will be used as a target (your exchange)
    market_id: bakeidr                                    # Market pair code in lowercase, from your target exchange
  sources:
  - account_id: binance_source                            # Unique account id, from the account section, that will be used as a source
    market_id: BAKEUSDT                                   # Market pair code in uppercase, from you source exchange
